Update patch set 11
Patch Set 11: Code-Review-1 Verified-1

Hi Icaro, I'm doing some tests using this patch and some errors are happening when I try to create an Intent-NBI using the RESTConf.
==============================
2016-11-10 23:26:48,382 | ERROR | config-pusher    | ConfigPusherImpl                 | 135 - org.opendaylight.controller.config-persister-impl - 0.6.0.SNAPSHOT | Unable to push configuration due to missing yang models. Yang models that are missing, but required by the configuration: [urn:onf:intent:intent:nbi?module=intent-nbi&revision=2016-09-20, urn:opendaylight:nic:listeners?module=intent-listeners&revision=2015-09-16]. For each mentioned model check:  1. that the mentioned yang model namespace/name/revision is identical to those in the yang model itself 2. the yang file is present in the system 3. the bundle with that yang file is present in the system and active 4. the yang parser did not fail while attempting to parse that model
2016-11-10 23:26:48,383 | ERROR | config-pusher    | ConfigPusherImpl                 | 135 - org.opendaylight.controller.config-persister-impl - 0.6.0.SNAPSHOT | Failed to apply configuration snapshot: 92-intent-listeners.xml(odl-nic-listeners,odl-nic-listeners)
java.lang.IllegalStateException: Unable to push configuration due to missing yang models. Required yang models that are missing: [urn:onf:intent:intent:nbi?module=intent-nbi&revision=2016-09-20, urn:opendaylight:nic:listeners?module=intent-listeners&revision=2015-09-16]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.waitForCapabilities(ConfigPusherImpl.java:208)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.pushConfigWithConflictingVersionRetries(ConfigPusherImpl.java:158)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.internalPushConfigs(ConfigPusherImpl.java:128)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.processSingle(ConfigPusherImpl.java:82)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.process(ConfigPusherImpl.java:74)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.osgi.ConfigPersisterActivator$2.run(ConfigPersisterActivator.java:131)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: org.opendaylight.controller.config.persist.impl.ConfigPusherImpl$NotEnoughCapabilitiesException: Not enough capabilities for 92-intent-listeners.xml(odl-nic-listeners,odl-nic-listeners). Expected but not found: [urn:onf:intent:intent:nbi?module=intent-nbi&revision=2016-09-20, urn:opendaylight:nic:listeners?module=intent-listeners&revision=2015-09-16]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.waitForCapabilities(ConfigPusherImpl.java:188)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
        ... 6 more
=================================

Patch-set: 11